implement list app widget
phongnhat19/portal-builder-client pull request #48
Opened 2020-04-24 07:13 UTC by Pham-Gia-Huong

2020-04-24 10:03 UTC, phongnhat19 requested changes

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Layout/GridLayout/GridBlock/index.tsx
> +          break;
Re-run eslint on this code block

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Layout/GridLayout/GridBlock/index.tsx
> +          };
Re-run eslint on this code block

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Layout/GridLayout/GridBlock/renderer.tsx
> +            break;
Re-run eslint on this code block

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Layout/TabsLayout/index.tsx
> +          break;
Re-run eslint on this code block

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/AppSpaceModel.tsx
> +import RenderCategoryDetail from './components/categoryList';
Module name is `CategoryList` not `categoryList`

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/AppSpaceModel.tsx
> +        />
Re-run eslint here

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/AppSpaceModel.tsx
> +  let listCategory = newData.listCategory as CategorytAppSpace[];
Re-run eslint here

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/AppSpaceModel.tsx
> +  i: number;
Rename props for clear meaning

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/AppSpaceModel.tsx
> +const RenderBlockCategory = ({
Component name should be a noun, not a verb

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/AppSpaceModel.tsx
> +const RenderCategory = ({
Component name should be a noun, not a verb

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/AppSpaceModel.tsx
> +const RenderActionAddCategory = ({
Component name should be a noun, not a verb

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/AppSpaceModel.tsx
> +        listCategory={listCategory}
Should be `categoryList`, not `listCategory`

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/AppSpaceModel.tsx
> +          }}
Could be change to `onClick={onChange}` for shorter code

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/AppSpaceModel.tsx
> +  );
Re-run eslint here

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/AppSpaceModel.tsx
> +  i,
Rename props for clear meaning

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/AppSpaceModel.tsx
> +          </React.Fragment>
No need to wrap inside a `React.Fragment` component

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/AppSpaceModel.tsx
> +    let category: ModalAppSpace = {listCategory: [{type: 'app', id: '', name: '', icon: ''}], category: ''};
Re-run eslint

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/AppSpaceModel.tsx
> +      {i > 0 ? <MinusCircleFilled onClick={() => handleRemoveCategory()} /> : ''}
Should be `{i > 0 && <MinusCircleFilled onClick={() => handleRemoveCategory()} />}`

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/AppSpaceModel.tsx
> +      }}
Should be `onCancel={onCancel}`

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/AppSpaceModel.tsx
> +      />
Re-run eslint

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/components/CategoryList.tsx
> +  let newListCategory = listCategory.slice();
Re-run eslint

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/components/CategoryList.tsx
> +          {i > 0 ? <MinusCircleFilled style={{color:"#1890ff"}} onClick={() => removeRow(i)} /> : ''}
Should be `{i > 0 && <MinusCircleFilled style={{color:"#1890ff"}} onClick={() => removeRow(i)} />}`

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/components/CategoryList.tsx
> +        <InputText
Rename component for clear meaning (for example `InputWithLabel`)

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/components/DropDownType.tsx
> +      <a className="ant-dropdown-link" onClick={(e) => e.preventDefault()}>
Re-run eslint here

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/components/DropDownType.tsx
> +const DropDownType = ({value, onChange}: {value: string; onChange: (value: string) => void}) => {
Should be `TypeDropdown`, not `DropDownType`

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/components/InputWidget.tsx
> +    <div className={`item-block ` + className}  style={{width}}>
Re-run eslint here

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/components/InputWidget.tsx
> +  className:string;
Re-run eslint here

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/components/InputWidget.tsx
> +export const InputText = ({
Component name should be consistent with file name

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/components/InputWidget.tsx
> +    <div className={`item-block ` + className}  style={{width}}>
Should be ``className={`item-block ${className}`}``

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/components/PreviewContent.tsx
> +  let appType = type === 'app';
Re-run eslint here

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/components/PreviewContent.tsx
> +  let appType = type === 'app';
A boolean variable should be name as `isTypeApp`

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/components/PreviewContent.tsx
> +const PreviewContent = ({listContent}: {listContent: ModalAppSpace[]}) => {
Should be `contentList`, not `listContent`

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/components/PreviewContent.tsx
> +const PreviewContent = ({listContent}: {listContent: ModalAppSpace[]}) => {
Re-run eslint here

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/components/PreviewContent.tsx
> +  };
Re-run eslint here

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/components/PreviewContent.tsx
> +              let hightLightRow= !numberEven ? "hight-light" : "";
Re-run eslint here

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/components/PreviewContent.tsx
> +              let numberEven = checkEvenNumber(i);
Boolean variable should be named `isEven`

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/components/PreviewContent.tsx
> +                </React.Fragment>
No need to wrap inside `React.Fragment` component

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/components/PreviewTitle.tsx
> +import { AppstoreFilled } from '@ant-design/icons';
Re-run eslint here

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/components/PreviewTitle.tsx
> +export default PreviewTitle
Re-run eslint here

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/index.tsx
> +      titleWidget={titleWidget}
Re-run eslint here

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/index.tsx
> +        getContent={({listContent, titleWidget}) => {
`listContent` and `titleWidget` is re-declared

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/index.tsx
> +          onSaveSetting && onSaveSetting({listContent:newListContent, titleWidget});
Re-run eslint here

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/rerender.tsx
> +  useEffect(() => {
Re-run eslint

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/service.ts
> +  let newListAppSpace = listAppSpace.slice();
Re-run eslint

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/service.ts
> +const getAppInfo: ({listAppSpace}: {listAppSpace: ModalAppSpace[]}) => Promise<ModalAppSpace[]> = async ({
Rename `ModalAppSpace` for clear meaning

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/type.d.ts
> +  isSave:boolean
Re-run eslint

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/AppSpaceListWidget/type.d.ts
> +  isSave:boolean
`isSave` property is not used

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/Widget/constant.ts
> +  APP_SPACE:"App/Space"
Re-run eslint

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/views/PortalBuilder/index.tsx
> +    },
Re-run eslint

2020-04-24 10:03 UTC, phongnhat19 commented on src/renderer/views/PortalBuilder/index.tsx
> +      </div>
Re-run eslint

2020-04-27 03:05 UTC, Pham-Gia-Huong commented on src/renderer/Widget/AppSpaceListWidget/AppSpaceModel.tsx
> +          </React.Fragment>
I think need React.Fragment, consolog will show error due map need a key key unique.

2020-04-27 03:05 UTC, Pham-Gia-Huong commented on src/renderer/Widget/AppSpaceListWidget/components/PreviewContent.tsx
> +                </React.Fragment>
I think need React.Fragment, consolog will show error due map need a key key unique.

2020-04-29 07:33 UTC, phongnhat19 approved these changes

2020-05-13 08:02 UTC, phongnhat19 requested changes

2020-05-13 08:02 UTC, phongnhat19 commented on src/renderer/Layout/TabsLayout/style.css
> +  min-width: 98%;
Should be 
```
min-width: 100%;
box-sizing: border-box;
```

2020-05-14 02:52 UTC, merged